baseURL = 'https://slides.luhack.uk'
languageCode = 'en-gb'
title = 'LUHack Slides'
theme = "slideout"

[Params]
  logo = "/img/luhack_logo.svg"
  author = "LUHack"
  highlightColor = "#b5111a"

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
  noClasses = false
  pygmentsUseClasses = true
  pygmentsCodefences = true

[markup.goldmark.renderer]
  unsafe = true
